#!/bin/bash
#SBATCH --job-name=post_sspace_pilon
#SBATCH --output=log/pilon_round2_%j.out
#SBATCH --error=log/pilon_round2_%j.err
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=40
#SBATCH --mem=250G



# --- DIRECTORIES ---
SSPACE_DIR="result/sspaces"
OUT_DIR="result/final_polished"

# IMPORTANT: Point this to where your clean, compressed reads are stored.
# (Likely 'result/k2' or 'result/fastp')
READ_DIR="result/k2" 

# Verify the JAR path exists
PILON_JAR="/home/huyha/micromamba/envs/pilon/share/pilon-1.24-0/pilon.jar"

mkdir -p "$OUT_DIR"

# Loop through the Final Scaffolds generated by the refined SSPACE script
# Matches pattern: result/sspaces/SAMPLE_scaffold/SAMPLE_final_scaffolds.fasta
for scaffold_in in ${SSPACE_DIR}/*_scaffold/*.final.scaffolds.fasta; do

    # 1. Extract Sample Name
    # Filename format is: SAMPLE_final_scaffolds.fasta
    filename=$(basename "$scaffold_in")
    sample=$(echo "$filename" | sed 's/_sspace.final.scaffolds.fasta//')

    echo "=== Round 2 Polishing for Sample: $sample ==="

    WORK_DIR="${OUT_DIR}/${sample}"
    mkdir -p "$WORK_DIR"
    
    # Check if this sample is already finished
    if [[ -s "${WORK_DIR}/${sample}_final_polished.fasta" ]]; then
        echo "--- Polished file exists for $sample. Skipping. ---"
        continue
    fi

    # 2. Define Read Inputs (Use original .gz files)
    fq1="${READ_DIR}/clean.trim.${sample}_1.fq.gz"
    fq2="${READ_DIR}/clean.trim.${sample}_2.fq.gz"
    

    # Verify inputs exist
    if [[ ! -f "$fq1" || ! -f "$fq2" ]]; then
        echo "Error: Reads for $sample not found in $READ_DIR. Skipping."
        continue
    fi

    # 3. Index the NEW Scaffolds (if missing)
    if [[ ! -f "${scaffold_in}.bwt" ]]; then
        echo "--- Indexing Scaffolds for $sample ---"
        micromamba run -n bwa bwa index "$scaffold_in"
        micromamba run -n bwa samtools faidx "$scaffold_in"
    fi

    # 4. Align reads to Scaffolds
    # Creating a temp BAM file. 
    # Optimization: 40 CPUs total = 30 for BWA + 10 for Sorting
    echo "--- Aligning reads to scaffolds for $sample ---"
    
    micromamba run -n bwa bwa mem -t 30 "$scaffold_in" "$fq1" "$fq2" | \
        micromamba run -n bwa samtools sort -@ 10 -m 4G -o "${WORK_DIR}/${sample}_scaffold.sorted.bam" -
    
    micromamba run -n bwa samtools index  "${WORK_DIR}/${sample}_scaffold.sorted.bam"

    # 5. Run Pilon (Round 2)
    echo "--- Running Pilon Round 2 for $sample ---"
    
    micromamba run -n pilon java -Xmx200G -jar "$PILON_JAR" \
        --genome "$scaffold_in" \
        --frags "${WORK_DIR}/${sample}_scaffold.sorted.bam" \
        --output "${sample}_final_polished" \
        --outdir "$WORK_DIR" \
        --fix all \
        --changes \
        --threads 40

    # 6. Cleanup BAM to save space (Optional but recommended)
    # rm "${WORK_DIR}/${sample}_scaffold.sorted.bam" "${WORK_DIR}/${sample}_scaffold.sorted.bam.bai"

    echo "=== Finished Round 2 for Sample $sample ==="
done